<?
$PERM["/"]["*"]="R";
$PERM["personal"]["5"]="W";
$PERM["personal"]["8"]="W";
$PERM["catalog"]["5"]="W";
$PERM["catalog"]["8"]="W";
$PERM["news"]["5"]="W";
$PERM["news"]["8"]="W";
$PERM["about"]["5"]="W";
$PERM["about"]["8"]="W";
$PERM["index.php"]["5"]="W";
$PERM["local"]["7"]="W";
?>