<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
use Sotbit\Origami\Helper\Config;
$APPLICATION->SetTitle("Сотрудники");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:news",
	"sotbit_origami_staff",
	array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "N",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "PREVIEW_TEXT",
			1 => "PREVIEW_PICTURE",
			2 => "DETAIL_TEXT",
			3 => "DETAIL_PICTURE",
			4 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "ORIGAMI_B24",
			1 => "ORIGAMI_MAIN_EMAIL",
			2 => "ORIGAMI_FB",
			3 => "ORIGAMI_INST",
			4 => "ORIGAMI_MAIL_RU",
			5 => "ORIGAMI_SKYPE",
			6 => "ORIGAMI_TELEGRAM",
			7 => "ORIGAMI_TWITTER",
			8 => "ORIGAMI_VK",
			9 => "ORIGAMI_ASK_QUESTION",
			10 => "ORIGAMI_POSITION",
			11 => "ORIGAMI_OK",
			12 => "ORIGAMI_EXPERIENCE",
			13 => "ORIGAMI_USER",
			14 => "ORIGAMI_MAIN_TEL",
			15 => "ORIGAMI_CERTIFICATES",
			16 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "N",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
        "IBLOCK_ID" => Config::get("IBLOCK_ID_EMPLOYEES"),
        "IBLOCK_TYPE" => Config::get("IBLOCK_TYPE_EMPLOYEES"),
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DETAIL_PICTURE",
			2 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "ORIGAMI_B24",
			1 => "ORIGAMI_MAIN_EMAIL",
			2 => "ORIGAMI_FB",
			3 => "ORIGAMI_INST",
			4 => "ORIGAMI_MAIL_RU",
			5 => "ORIGAMI_SKYPE",
			6 => "ORIGAMI_TELEGRAM",
			7 => "ORIGAMI_TWITTER",
			8 => "ORIGAMI_VK",
			9 => "ORIGAMI_ASK_QUESTION",
			10 => "ORIGAMI_POSITION",
			11 => "ORIGAMI_OK",
			12 => "ORIGAMI_EXPERIENCE",
			13 => "ORIGAMI_USER",
			14 => "ORIGAMI_MAIN_TEL",
			15 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "origami",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_FOLDER" => "/staff/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SORT_BY1" => "SORT",
		"SORT_BY2" => "NAME",
		"SORT_ORDER1" => "ASC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "Y",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"COMPONENT_TEMPLATE" => "sotbit_origami_staff",
		"MAIN_TEL" => "ORIGAMI_MAIN_TEL",
		"MAIN_EMAIL" => "ORIGAMI_MAIN_EMAIL",
		"PROPERTIES_SOCIAL_NETWORK" => array(
			0 => "ORIGAMI_FB",
			1 => "ORIGAMI_SKYPE",
			2 => "ORIGAMI_TWITTER",
			3 => "ORIGAMI_VK",
			4 => "ORIGAMI_INST",
			5 => "ORIGAMI_OK",
			6 => "ORIGAMI_TELEGRAM",
			7 => "ORIGAMI_MAIL_RU",
			8 => "ORIGAMI_B24",
			9 => "",
		),
		"FILTER_NAME" => "staff",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"PROPERTIES_DISPLAYED_ON_DETAIL" => array(
			0 => "ORIGAMI_POSITION",
			1 => "ORIGAMI_MAIN_TEL",
			2 => "ORIGAMI_MAIN_EMAIL",
			3 => "ORIGAMI_EXPERIENCE",
			4 => "",
		),
		"USER_DISPLAYED_FIELDS" => array(
			0 => "FIELD_EMAIL",
			1 => "PERSONAL_PROFESSION",
			2 => "PERSONAL_WWW",
			3 => "PERSONAL_ICQ",
			4 => "PERSONAL_GENDER",
			5 => "PERSONAL_BIRTHDAY",
			6 => "PERSONAL_PHONE",
			7 => "PERSONAL_FAX",
			8 => "PERSONAL_MOBILE",
			9 => "PERSONAL_PAGER",
			10 => "PERSONAL_STREET",
			11 => "PERSONAL_MAILBOX",
			12 => "PERSONAL_CITY",
			13 => "PERSONAL_STATE",
			14 => "PERSONAL_ZIP",
			15 => "PERSONAL_COUNTRY",
			16 => "PERSONAL_NOTES",
			17 => "WORK_COMPANY",
			18 => "WORK_DEPARTMENT",
			19 => "WORK_POSITION",
			20 => "WORK_WWW",
			21 => "WORK_PHONE",
			22 => "WORK_FAX",
			23 => "WORK_PAGER",
			24 => "WORK_STREET",
			25 => "WORK_MAILBOX",
			26 => "WORK_CITY",
			27 => "WORK_STATE",
			28 => "WORK_ZIP",
			29 => "WORK_COUNTRY",
			30 => "WORK_PROFILE",
			31 => "WORK_NOTES",
			32 => "",
		),
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
