name: Deploy Website

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy-production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Deploy to production via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: turbot.beget.ru
          username: novik5ga_github
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/n/novik5ga/stage.sportgroupstore.ru/public_html
            git config core.sshCommand "ssh -i /home/n/novik5ga/stage.sportgroupstore.ru/public_html/.ssh/id_rsa_project -F /dev/null -o UserKnownHostsFile=/home/n/novik5ga/stage.sportgroupstore.ru/public_html/.ssh/known_hosts -o StrictHostKeyChecking=yes"
            git config safe.directory /home/n/novik5ga/stage.sportgroupstore.ru/public_html
            git fetch origin master
            git reset --hard origin/master

  deploy-test:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Deploy to test via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: turbot.beget.ru
          username: novik5ga_github
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/n/novik5ga/dev.sportgroupstore.ru/public_html
            git config core.sshCommand "ssh -i /home/n/novik5ga/stage.sportgroupstore.ru/public_html/.ssh/id_rsa_project -F /dev/null -o UserKnownHostsFile=/home/n/novik5ga/stage.sportgroupstore.ru/public_html/.ssh/known_hosts -o StrictHostKeyChecking=yes"
            git config safe.directory /home/n/novik5ga/dev.sportgroupstore.ru/public_html
            if [ ! -d .git ]; then
              git init
              git remote add origin git@github.com:ergopromo/sportgroupstore.ru.git
            fi
            git fetch origin dev
            git checkout -B dev origin/dev
            git reset --hard origin/dev
